[project]
name = "2026-data-engineering-zoomcamp-homeworks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "sqlalchemy>=2.0.46",
]
