services:
  pgdatabase:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ny_taxi"
    ports:
      - "5433:5432"
    volumes:
      - vol-pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

  data_ingest:
    image: data_ingest:v0.1
    container_name: data_ingest
    command:
      - --pg-user=root
      - --pg-pass=root
      - --pg-host=pgdatabase
      - --pg-port=5432
      - --pg-db=ny_taxi
      - --table-name=yellow_taxi_trips
    depends_on:
      pgdatabase:
        condition: service_healthy

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:
